## Fetch the remote terraform module
deps:
	@if (aws s3 ls s3://$${TF_BUCKET}/tfstate-backend/terraform.tfstate > /dev/null 2>&1); then \
			terraform init ; \
		else \
			terraform init -backend=false && \
			scripts/init.sh ; \
	fi

## Reset this project
reset:
	rm -rf Makefile *.tf .terraform
